'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class HR_EmployeeEdit

    Protected WithEvents litFormTitle As Literal
    Protected WithEvents txtEmployeeCode As TextBox
    Protected WithEvents txtFullName As TextBox
    Protected WithEvents txtPosition As TextBox
    Protected WithEvents txtDepartment As TextBox
    Protected WithEvents txtEmail As TextBox
    Protected WithEvents txtPhone As TextBox
    Protected WithEvents txtAddress As TextBox
    Protected WithEvents txtHireDate As TextBox
    Protected WithEvents ddlStatus As DropDownList
    Protected WithEvents txtBaseSalary As TextBox
    Protected WithEvents ddlUser As DropDownList
    Protected WithEvents txtBankName As TextBox
    Protected WithEvents txtBankAccountNo As TextBox
    Protected WithEvents btnSave As Button

End Class
