'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class HR_Employees

    Protected WithEvents gvEmployees As GridView

End Class
