'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class HR_PayrollRun

    Protected WithEvents litPeriodName As Literal
    Protected WithEvents litPayDate As Literal
    Protected WithEvents litTotalNet As Literal
    Protected WithEvents lblStatusBadge As HtmlGenericControl
    Protected WithEvents litMessage As Literal
    Protected WithEvents gvDetails As GridView
    Protected WithEvents pnlDraftActions As Panel
    Protected WithEvents pFinalizedNote As HtmlGenericControl
    Protected WithEvents btnSaveChanges As Button
    Protected WithEvents btnFinalize As Button

End Class
