'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class HR_PayrollPeriodEdit

    Protected WithEvents litMessage As Literal
    Protected WithEvents ddlMonth As DropDownList
    Protected WithEvents txtYear As TextBox
    Protected WithEvents txtPayDate As TextBox
    Protected WithEvents btnGenerate As Button

End Class
