'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Finance_InvoiceEdit

    Protected WithEvents litFormTitle As Literal
    Protected WithEvents lblInvoiceNo As Label
    Protected WithEvents ddlSalesOrder As DropDownList
    Protected WithEvents ddlCustomer As DropDownList
    Protected WithEvents txtTotalAmount As TextBox
    Protected WithEvents txtInvoiceDate As TextBox
    Protected WithEvents txtDueDate As TextBox
    Protected WithEvents ddlStatus As DropDownList
    Protected WithEvents txtNotes As TextBox
    Protected WithEvents litMessage As Literal
    Protected WithEvents btnSave As Button

End Class
