'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Finance_InvoicePayments

    Protected WithEvents litInvoiceNo As Literal
    Protected WithEvents lnkPrint As HtmlAnchor
    Protected WithEvents litCustomer As Literal
    Protected WithEvents litTotal As Literal
    Protected WithEvents litPaid As Literal
    Protected WithEvents litOutstanding As Literal
    Protected WithEvents litDueDate As Literal
    Protected WithEvents lblStatusBadge As HtmlGenericControl
    Protected WithEvents litMessage As Literal
    Protected WithEvents txtAmount As TextBox
    Protected WithEvents txtPaymentDate As TextBox
    Protected WithEvents ddlMethod As DropDownList
    Protected WithEvents txtReference As TextBox
    Protected WithEvents txtNotes As TextBox
    Protected WithEvents btnAddPayment As Button
    Protected WithEvents gvPayments As GridView

End Class
