'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Finance_Invoices

    Protected WithEvents litTotalOutstanding As Literal
    Protected WithEvents litOverdueCount As Literal
    Protected WithEvents litTotalPaid As Literal
    Protected WithEvents gvInvoices As GridView

End Class
