'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Sales_SalesOrderEdit

    Protected WithEvents litFormTitle As Literal
    Protected WithEvents lblOrderNo As Label
    Protected WithEvents ddlCustomer As DropDownList
    Protected WithEvents ddlStatus As DropDownList
    Protected WithEvents txtNotes As TextBox
    Protected WithEvents pnlAddLine As Panel
    Protected WithEvents pLockedNotice As HtmlGenericControl
    Protected WithEvents ddlItem As DropDownList
    Protected WithEvents txtUnitPrice As TextBox
    Protected WithEvents txtQty As TextBox
    Protected WithEvents btnAddLine As Button
    Protected WithEvents litMessage As Literal
    Protected WithEvents gvLines As GridView
    Protected WithEvents litGrandTotal As Literal
    Protected WithEvents btnSave As Button

End Class
