'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Admin_UserEdit

    Protected WithEvents litFormTitle As Literal
    Protected WithEvents litMessage As Literal
    Protected WithEvents txtUsername As TextBox
    Protected WithEvents txtFullName As TextBox
    Protected WithEvents ddlRole As DropDownList
    Protected WithEvents lblPasswordLabel As HtmlGenericControl
    Protected WithEvents txtPassword As TextBox
    Protected WithEvents hintPassword As HtmlGenericControl
    Protected WithEvents chkIsActive As CheckBox
    Protected WithEvents btnSave As Button

End Class
