'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class CRM_CustomerEdit

    Protected WithEvents litFormTitle As Literal
    Protected WithEvents txtCompanyName As TextBox
    Protected WithEvents txtContactName As TextBox
    Protected WithEvents txtEmail As TextBox
    Protected WithEvents txtPhone As TextBox
    Protected WithEvents txtAddress As TextBox
    Protected WithEvents txtIndustry As TextBox
    Protected WithEvents ddlStatus As DropDownList
    Protected WithEvents txtNotes As TextBox
    Protected WithEvents btnSave As Button

End Class
