'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Projects_ProjectEdit

    Protected WithEvents litFormTitle As Literal
    Protected WithEvents txtProjectCode As TextBox
    Protected WithEvents txtProjectName As TextBox
    Protected WithEvents ddlCustomer As DropDownList
    Protected WithEvents ddlSalesOrder As DropDownList
    Protected WithEvents txtStartDate As TextBox
    Protected WithEvents txtEndDate As TextBox
    Protected WithEvents ddlStatus As DropDownList
    Protected WithEvents txtProjectManager As TextBox
    Protected WithEvents txtBudget As TextBox
    Protected WithEvents txtDescription As TextBox
    Protected WithEvents btnSave As Button

End Class
