'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Projects_ProjectTasks

    Protected WithEvents litProjectName As Literal
    Protected WithEvents txtTaskName As TextBox
    Protected WithEvents txtAssignedTo As TextBox
    Protected WithEvents txtStartDate As TextBox
    Protected WithEvents txtDueDate As TextBox
    Protected WithEvents ddlPriority As DropDownList
    Protected WithEvents ddlStatus As DropDownList
    Protected WithEvents btnAddTask As Button
    Protected WithEvents gvTasks As GridView

End Class
