'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class ChangePassword

    Protected WithEvents litMessage As Literal
    Protected WithEvents txtCurrentPassword As TextBox
    Protected WithEvents txtNewPassword As TextBox
    Protected WithEvents txtConfirmPassword As TextBox
    Protected WithEvents btnChangePassword As Button

End Class
