'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Default_Dashboard

    Protected WithEvents litTotalCustomers As Literal
    Protected WithEvents litTotalLeads As Literal
    Protected WithEvents litSOThisMonth As Literal
    Protected WithEvents litActiveProjects As Literal
    Protected WithEvents litLowStock As Literal
    Protected WithEvents litOutstandingInvoice As Literal
    Protected WithEvents litNetIncomeMonth As Literal
    Protected WithEvents litChartScript As Literal
    Protected WithEvents gvRecentSO As GridView
    Protected WithEvents gvRecentProjects As GridView

End Class
