'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Login

    Protected WithEvents txtUsername As TextBox
    Protected WithEvents txtPassword As TextBox
    Protected WithEvents btnLogin As Button
    Protected WithEvents litError As Literal

End Class
