'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class SiteMaster

    Protected WithEvents navDashboard As HtmlAnchor
    Protected WithEvents navCustomers As HtmlAnchor
    Protected WithEvents navSalesOrders As HtmlAnchor
    Protected WithEvents navItems As HtmlAnchor
    Protected WithEvents navWarehouses As HtmlAnchor
    Protected WithEvents navStock As HtmlAnchor
    Protected WithEvents navInvoices As HtmlAnchor
    Protected WithEvents navChartOfAccounts As HtmlAnchor
    Protected WithEvents navJournalEntries As HtmlAnchor
    Protected WithEvents navTrialBalance As HtmlAnchor
    Protected WithEvents navIncomeStatement As HtmlAnchor
    Protected WithEvents navBalanceSheet As HtmlAnchor
    Protected WithEvents navEmployees As HtmlAnchor
    Protected WithEvents navPayroll As HtmlAnchor
    Protected WithEvents navProjects As HtmlAnchor
    Protected WithEvents navSalesReport As HtmlAnchor
    Protected WithEvents navStockReport As HtmlAnchor
    Protected WithEvents navUsers As HtmlAnchor
    Protected WithEvents pnlFinanceGroup As Panel
    Protected WithEvents pnlHRGroup As Panel
    Protected WithEvents pnlReportsGroup As Panel
    Protected WithEvents pnlAdminGroup As Panel
    Protected WithEvents litNotifCount As Literal
    Protected WithEvents litNotifDropdown As Literal
    Protected WithEvents litUserName As Literal
    Protected WithEvents lnkLogout As LinkButton

End Class
