'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Inventory_ItemEdit

    Protected WithEvents litFormTitle As Literal
    Protected WithEvents txtItemCode As TextBox
    Protected WithEvents txtItemName As TextBox
    Protected WithEvents ddlItemType As DropDownList
    Protected WithEvents txtCategory As TextBox
    Protected WithEvents txtUnit As TextBox
    Protected WithEvents txtUnitPrice As TextBox
    Protected WithEvents txtReorderLevel As TextBox
    Protected WithEvents btnSave As Button

End Class
