'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Inventory_StockMovements

    Protected WithEvents ddlItem As DropDownList
    Protected WithEvents ddlWarehouse As DropDownList
    Protected WithEvents ddlMovementType As DropDownList
    Protected WithEvents txtQuantity As TextBox
    Protected WithEvents txtNotes As TextBox
    Protected WithEvents litMessage As Literal
    Protected WithEvents btnSubmit As Button
    Protected WithEvents gvMovements As GridView

End Class
