'------------------------------------------------------------------------------
' <auto-generated>
'     File ini berisi deklarasi control (Protected WithEvents) untuk halaman terkait.
'     Dipisah dari file .vb utama supaya kalau Visual Studio meregenerasi file ini,
'     tidak terjadi deklarasi dobel (duplicate declaration).
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public Class Inventory_Warehouses

    Protected WithEvents txtWarehouseName As TextBox
    Protected WithEvents txtLocation As TextBox
    Protected WithEvents btnAdd As Button
    Protected WithEvents gvWarehouses As GridView

End Class
